sudo: false

os:
  # - osx TODO: reenable after osx seems a little less buggy on travis
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  # - npm run vscode:prepublish TODO: need to investigate if this is necessary or why it fails

script:
  - npm test --silent